<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>BAI - {{ $order->customer_name }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #1a1a2e; padding: 20px; }
        h1   { font-size: 18px; text-align: center; margin-bottom: 4px; }
        h2   { font-size: 14px; text-align: center; margin-bottom: 20px; color: #555; }
        .row { display: table; width: 100%; margin-bottom: 6px; }
        .col { display: table-cell; padding: 4px 8px; }
        .label { font-weight: 600; width: 30%; }
        .val { }
        hr { border: 1px solid #e0e0e0; margin: 12px 0; }
        .sig-block { margin-top: 30px; text-align: center; }
        .sig-box { display: inline-block; width: 240px; height: 80px; border: 1px solid #333; }
        .sig-box img { max-width: 100%; max-height: 100%; }
        .small { font-size: 10px; color: #777; }
        table { width: 100%; border-collapse: collapse; margin-top: 8px; }
        td, th { padding: 5px; border: 1px solid #ccc; text-align: left; }
    </style>
</head>
<body>
    <h1>BERITA ACARA INSTALASI (BAI)</h1>
    <h2>Penyambungan Baru Layanan Internet - {{ config('app.name') }}</h2>

    <table>
        <tr><th colspan="2" style="background:#f0f0f0">DATA PELANGGAN</th></tr>
        <tr><td class="label">No. Order</td><td>#{{ str_pad($order->id, 5, '0', STR_PAD_LEFT) }}</td></tr>
        <tr><td class="label">Nama</td><td>{{ $order->customer_name }}</td></tr>
        <tr><td class="label">No. HP</td><td>{{ $order->customer_phone }}</td></tr>
        <tr><td class="label">NIK</td><td>{{ $order->customer_nik ?? '-' }}</td></tr>
        <tr><td class="label">Alamat</td><td>{{ $order->customer_address }} (RT {{ $order->rt }}/RW {{ $order->rw }}, {{ $order->village ?? '' }}, {{ $order->district ?? '' }})</td></tr>
        <tr><td class="label">Paket</td><td>{{ $order->package }}</td></tr>
    </table>

    <table>
        <tr><th colspan="2" style="background:#f0f0f0">DATA TEKNIS</th></tr>
        <tr><td class="label">OLT</td><td>{{ strtoupper($order->olt_type?->value ?? '-') }} (Port: {{ $order->olt_port_label ?? '-' }}, SN: {{ $order->onu_serial ?? '-' }})</td></tr>
        <tr><td class="label">ODP</td><td>{{ $order->odp_code ?? '-' }} (Jarak: {{ round($order->odp_distance_m ?? 0) }} m)</td></tr>
        <tr><td class="label">Router</td><td>{{ $order->router_name }}</td></tr>
        <tr><td class="label">PPPoE User</td><td>{{ $order->pppoe_user }}</td></tr>
        <tr><td class="label">PPPoE Password</td><td>{{ $order->pppoe_password }}</td></tr>
        <tr><td class="label">Redaman ODP</td><td>{{ $order->redaman_odp ?? '-' }} dB</td></tr>
        <tr><td class="label">Redaman Router</td><td>{{ $order->redaman_router ?? '-' }} dB</td></tr>
        <tr><td class="label">GPS</td><td>{{ $order->gps_lat }}, {{ $order->gps_long }}</td></tr>
        <tr><td class="label">Teknisi</td><td>{{ $order->teknisi->pluck('name')->join(', ') }}</td></tr>
    </table>

    <p style="margin-top: 20px;">
        Dengan ini pelanggan menyatakan bahwa pemasangan internet telah selesai dilakukan
        dan koneksi internet sudah dapat digunakan dengan baik. Pelanggan menyetujui
        <i>Berita Acara Instalasi</i> ini untuk diteruskan ke sistem eBilling.
    </p>

    <div class="sig-block">
        <div class="col" style="width:50%; float:left;">
            <p>Pelanggan,</p>
            <div class="sig-box"><img src="{{ $signature }}" alt="ttd"></div>
            <p class="small">{{ $order->customer_name }}<br>Tgl: {{ $order->bai_signed_at?->format('d-m-Y H:i') }}</p>
        </div>
        <div class="col" style="width:50%; float:right;">
            <p>Teknisi,</p>
            <div class="sig-box" style="border: none; height: 80px;"></div>
            <p class="small">{{ $order->teknisi->pluck('name')->join(', ') }}</p>
        </div>
    </div>

    <hr>
    <p class="small" style="text-align: center;">
        Generated by {{ config('app.name') }} at {{ now()->format('d-m-Y H:i') }} |
        Order #{{ $order->id }}
    </p>
</body>
</html>
